module.exports = {
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    "airbnb",
    "plugin:react/recommended",
    "plugin:jsx-a11y/recommended",
    "plugin:import/errors",
    "plugin:import/warnings",
    "plugin:@typescript-eslint/recommended",
    "plugin:prettier/recommended",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: "latest",
    sourceType: "module",
  },
  plugins: ["@typescript-eslint", "prettier"],
  ignorePatterns: ["dist/**.**"],
  rules: {
    "prettier/prettier": [
      "error",
      {
        singleQuote: true,
        semi: true,
        useTabs: false,
        tabWidth: 2,
        trailingComma: "all",
        printWidth: 200,
        arrowParens: "always",
        orderedImports: true,
        bracketSpacing: true,
        bracketSameLine: true,
        jsxBracketSameLine: false,
        endOfLine: "auto",
      },
    ],
    "no-alert": 0,
    "linebreak-style": 0,
    "import/prefer-default-export": 0,
    "import/extensions": 0,
    "no-use-before-define": 0,
    "import/no-unresolved": 0,
    "react/react-in-jsx-scope": 2,
    "import/no-extraneous-dependencies": 0,
    "no-shadow": 0,
    "import/no-dynamic-require": 0,
    "no-var-requires": 0,
    "no-empty-function": 0,
    "no-unused-expressions": [2, { allowShortCircuit: true }],
    "@typescript-eslint/no-empty-function": 0,
    "jsx-a11y/no-noninteractive-element-interactions": 0,
    "@typescript-eslint/no-inferrable-types": 0,
    "@typescript-eslint/explicit-module-boundary-types": 0,
    "@typescript-eslint/no-var-requires": 0,
    "@typescript-eslint/no-unused-vars": 2,
    "no-param-reassign": [
      "error",
      {
        props: true,
        ignorePropertyModificationsFor: ["e", "state"],
      },
    ],
    // react
    "react/prop-types": 0,
    "react/jsx-no-useless-fragment": 0,
    "react/jsx-filename-extension": [
      2,
      { extensions: [".js", ".jsx", ".ts", ".tsx"] },
    ],
    "react/require-default-props": 0,
    "react/jsx-props-no-spreading": 0,
    "react/function-component-definition": 0,
    "jsx-a11y/no-static-element-interactions": 0,
    "jsx-a11y/label-has-associated-control": 0,
  },
  settings: {
    "import/resolver": {
      node: {
        extensions: [".js", ".jsx", ".ts", ".tsx"],
      },
    },
  },
};
